### ISSUE TITLE
Real depth

### ISSUE THREAD

**Issue by jabrail-chumakov** [needle-mirror/com.unity.simulation.capture#1]
Hello folks! 

I have a question regarding depth mapping for this package. I'm trying to use depth script (DepthGrab.cs) together with a perception package and encountered some problems. 

1. The first problem is that I have stripes on rendered photos, which seems strange. How to make it more gradient? 
2. The second thing is whether this script gives true depth values or not? If I will collect the dataset will Unity depth camera (DepthGrab.cs applied) give the correct values as a real depth camera? Or this script is just a simulation of depth and not a real one.

Thanks in advance!

**Comment by marwie** [comment]
Hello,

please [report this issue to Unity directly](https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-#:~:text=Click%20on%20Help%2C%20and%20from,the%20Title%20and%20Details%20fields.), we are not officially affiliated and the issues here wont reach the devs otherwise unfortunately.

thanks
